import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-4xl py-12 px-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Terms & Conditions</CardTitle>
          <CardDescription>Last Updated: July 2024</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
          <p>
            By using this website, you agree to be roasted. If you cannot handle the heat, please exit the kitchen (or, you know, close the tab).
          </p>
          <h3 className="font-semibold text-foreground pt-4">Use of Service</h3>
          <p>
            Roast-My-Code is provided for entertainment purposes only. The roasts are generated by an AI and do not reflect my opinions. The content may be satirical, sarcastic, and humorous. Do not take it personally. If you do, that's a 'you' problem.
          </p>
           <h3 className="font-semibold text-foreground pt-4">Limitation of Liability</h3>
          <p>
            I am not responsible for any emotional damage, bruised egos, or sudden career changes that may result from using this service. Use at your own risk. I am also not liable if the AI becomes self-aware and starts roasting me.
          </p>
          <h3 className="font-semibold text-foreground pt-4">Changes to Terms</h3>
          <p>
            I reserve the right to change these terms at any time. I'll probably do it without telling you, just like that breaking change in your favorite framework.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
