import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto max-w-4xl py-12 px-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Disclaimer</CardTitle>
          <CardDescription>Last Updated: July 2024</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
          <p>
            The content provided on Roast-My-Code is for entertainment and informational purposes only. The roasts are generated by an artificial intelligence and are intended to be humorous. They do not represent factual statements or professional advice.
          </p>
          <p>
            The owners and operators of this website make no representations as to the accuracy, completeness, or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
          </p>
          <p>
            Any actions you take based upon the information on this website are strictly at your own risk. We will not be liable for any losses and damages in connection with the use of our website.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
